<?php

/**
 * Implements hook_block_info().
 */
function openlayers_block_switcher_block_info() {
  $maps = _olebs_get_maps_with_blockswitcher();
  $blocks = array();

  foreach ($maps as $key => $map) {
    $map = openlayers_object_load('map', $map->machine_name);
    if ($map->getOption('provideBlockLayerSwitcher', 0)) {
      $blockid = _olebs_get_block_id($key);
      $blocks[$blockid]['info'] = t('OpenLayers layer switcher for ' . $map->get('name'));
    }
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function openlayers_block_switcher_block_view($delta = '') {
  $block = array();
  $map = openlayers_object_load('map', _olebs_get_map_name($delta));

  $block['subject'] = $map->get('name');
  $form = drupal_get_form('olebs_blockswitcher_form', $map);
  $block['content'] = drupal_render($form);

  return $block;
}

/**
 * Helper function.
 * Returns maps with the blockswitcher behavior enabled.
 *
 * @return array
 */
function _olebs_get_maps_with_blockswitcher() {
  $maps = &drupal_static(__FUNCTION__);

  if (!isset($maps)) {
    ctools_include('export');
    $maps = ctools_export_crud_load_all('openlayers_maps');
  }

  return $maps;
}

/**
 * Helper function
 * Return the blocks delta according to the map_name.
 */
function _olebs_get_block_id($map_name) {
  return substr(sha1($map_name), 0, -32) . '_blockswitcher';
}

/**
 * Helper function
 * Return the map name according to the block delta.
 */
function _olebs_get_map_name($delta) {
  foreach (_olebs_get_maps_with_blockswitcher() as $map_name => $map) {
    if (_olebs_get_block_id($map_name) == $delta) {
      return $map_name;
    }
  }
  return FALSE;
}

/**
 * Form for the layer switcher.
 *
 * @param $form
 * @param $form_state
 * @param $map
 * @return mixed
 */
function olebs_blockswitcher_form($form, &$form_state, $map) {
  $default_value = array();
  $options_overlays = array();

  if ($layers = $map->getOption('layers')) {
    foreach($layers as $layer) {
      $layer = openlayers_object_load('layer', $layer->machine_name);
      $options_overlays[$layer->machine_name] = $layer->get('name');
      if ('1' == $layer->getOption('visible', 1)) {
        $default_value[] = $layer->machine_name;
      }
    }
  }

  if (!empty($options_overlays)) {
    $form['overlays']= array(
      '#title'   => t('Overlays'),
      '#type'    => 'checkboxes',
      '#options' => $options_overlays,
      '#default_value' => $default_value
    );
  }

  $form['map']= array(
    '#type'    => 'hidden',
    '#value' => $map->machine_name,
  );

  $form['#attached']['css'] = array();
  $form['#attached']['library'] = array();
  $form['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'openlayers_block_switcher') . '/olbs.js',
    'type' => 'file'
  );

  return $form;
}
