<?php

/**
 * @file
 * Main OpenLayers Test Module file
 *
 * This file contains a test module to help with automated
 * testing.
 *
 * @ingroup openlayers
 */

/**
 * Implements hook_menu().
 */
function openlayers_test_menu() {
  $items = array();

  $items['admin/structure/openlayers/test'] = array(
    'title' => 'OpenLayers Test Page',
    'description' => 'Test Page for OpenLayers.',
    'page callback' => 'openlayers_test_page',
    'access arguments' => array('administer openlayers'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 9999,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function openlayers_test_ctools_plugin_api($module, $api) {
  // Define plugins for OpenLayers plugins api
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_maps':
        return array('version' => 1);

    }
  }
}

/**
 * Implements hook_openlayers_maps().
 */
function openlayers_test_openlayers_maps() {
  module_load_include('inc', 'openlayers_test', 'includes/openlayers_test.maps');
  return _openlayers_test_openlayers_maps();
}

/**
 * Callback for OpenLayers Test Page
 */
function openlayers_test_page() {
  drupal_add_js(drupal_get_path('module', 'openlayers_test') . '/js/qunit/qunit.js');
  drupal_add_css(drupal_get_path('module', 'openlayers_test') . '/js/qunit/qunit.css');
  drupal_add_js(drupal_get_path('module', 'openlayers_test') . '/js/openlayers_test.js');
  $output = '';
  
  // Display QUnit stuff
  $output .= '
    <h1 id="qunit-header">OpenLayers QUnit Tests</h1>
    <h2 id="qunit-banner"></h2>
    <h2 id="qunit-userAgent"></h2>
    <ol id="qunit-tests"></ol>
  ';

  // Render all maps
  $maps = openlayers_maps();
  foreach ($maps as $name => $map) {
    $output .= '
      <h3>' . $map->title . '</h3>
      ' . openlayers_render_map($map) . '
    ';
  }

  /*
  // Create collapsed fieldset
  //$render_fieldset = openlayers_render_map();
  $element = array(
    '#value' => $render_fieldset['themed'],
    '#title' => t('Fieldset Example'),
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
  );
  $fieldset = theme_fieldset($element);
  */

  // Create output
  $output .= '
    <!-- Not including fieldset cause its broken -->
  ';

  return $output;
}

/**
 * Implements hook_views_api().
 */
function openlayers_test_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implements hook_views_default_views().
 */
function openlayers_test_views_default_views() {
  module_load_include('inc', 'openlayers_test', 'includes/openlayers_test.views');
  return _openlayers_test_views_default_views();
}

/**
 * Impements hook_openlayers_map_preprocess_alter().
 */
function openlayers_test_openlayers_map_preprocess_alter(&$map) {
  // For testing purposes, display a message on the only the Test
  // page, and only once.
  static $performed = FALSE;
  if (!$performed && $_GET['q'] == 'admin/structure/openlayers/test') {
    drupal_set_message(t('OpenLayers preprocess map alter hook fired.'));
    $performed = TRUE;
  }
}

/**
 * Impements hook_openlayers_map_alter().
 */
function openlayers_test_openlayers_map_alter(&$map) {
  // For testing purposes, display a message on the only the Test
  // page, and only once.
  static $performed = FALSE;
  if (!$performed && $_GET['q'] == 'admin/structure/openlayers/test') {
    drupal_set_message(t('OpenLayers map alter hook fired.'));
    $performed = TRUE;
  }
}