<?php
// $Id$

/**
 * @file
 * This file holds the main Drupal hook functions 
 * and private functions for the openlayers_cck module.
 *
 * @ingroup openlayers
 */

/**
 * Map ID Prefix
 */
define('OPENLAYERS_CCK_MAP_ID_PREFIX', 'openlayers-cck-map-auto-id');

/**
 * Implementation of hook_help
 */
function openlayers_cck_help($path, $arg) {
  switch ($path) {
    case 'admin/help#openlayers_cck':
      $output = '<p>'. t('The openlayers_cck module provides fields and widgets that interface with OpenLayers.') .'</p>';
  }
  
  return $output;
}

/**
 * Implementation of hook_theme().
 */
function openlayers_cck_theme() {
  $themes = array(
    'openlayers_cck_geo_field' => array(
      'arguments' => array(
        'element' => NULL
      ),
    ),
    'openlayers_cck_map' => array(
      'arguments' => array(
        'field' => NULL,
        'map' => NULL,
      ),
    ),
  );
    
  // Create formatter theme functions
  foreach (openlayers_get_presets() as $name => $title) {
    $themes['openlayers_cck_formatter_' . $name] = array(
      'arguments' => array('element' => NULL),
      'function' => 'theme_openlayers_cck_formatter',
    );
  }
  
  return $themes;
}

/**
 * Implementation of hook_gis_input_info().
 */
function openlayers_cck_gis_input_info($gis_type = NULL) {
  // Note, we shou use the following so that we can actually control how
  // the widget will work, butdifficult to make unlimited work
  // and Geo does not support it yet
  // 'multiple values' => CONTENT_HANDLE_MODULE,
  $inputs = array(
    'openlayers_cck_geo_field' => array(
      'label' => t('OpenLayers Map'),
      'gis input' => 'wkt',
      'safe reverse' => TRUE,
      'gis types' => array('point', 'linestring', 'polygon'),
      'element' => array(
        '#type' => 'openlayers_cck_geo_field',
      ),
    ),
  );
  return $inputs;
}

/**
 * Implementation of hook_field_info().
 */
function openlayers_cck_field_info() {
  return array(
    'openlayers_wkt' => array(
      'label' => t('OpenLayers WKT'),
      'description' => t('Input WKT data via an OpenLayers map.'),
      'callbacks' => array(
        'tables' => CONTENT_CALLBACK_DEFAULT,
        'arguments' => CONTENT_CALLBACK_DEFAULT,
        ),
    ),
  );
}

/**
 * Implementation of hook_field_settings
 */
function openlayers_cck_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $form = array();      
      return $form;

    case 'validate':
      break;

    case 'save':
      return array();

    case 'database columns':
      $columns = array(
        'openlayers_wkt' => array(
          'type' => 'text',
          'not null' => FALSE, 
          'sortable' => TRUE,
        ),
      );
      return $columns;
      
  }
}

/**
 * Implementation of hook_field
 */
function openlayers_cck_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    case 'validate':
      // Check if field is valid WKT format
      foreach($items as $delta => $value) {
        // @@TODO: validate WKT
      }
      break;
      
  }
}

/**
 * Implementation of hook_content_is_empty
 */
function openlayers_cck_content_is_empty($item, $field) {
  if (empty($item['openlayers_wkt'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_widget_info
 */
function openlayers_cck_widget_info() {
  return array(
    'openlayers_wkt_widget' => array(
      'label' => t('OpenLayers WKT Map Widget'),
      'field types' => array('openlayers_wkt'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
 * Implementation of hook_widget_settings
 */
function openlayers_cck_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      // Get Presets
      $presets = openlayers_get_presets();
      $default_preset = variable_get('openlayers_default_preset', 'default');
      
      $form['openlayers_cck_preset_map'] = array(
        '#type' => 'select',
        '#title' => t('Input Map Preset'),
        '#description' => t('Choose the OpenLayers Preset Map that will be used to input the WKT data.'),
        '#options' => $presets,
        '#default_value' => isset($widget['openlayers_cck_preset_map']) ? $widget['openlayers_cck_preset_map'] : $default_preset,
      );
      // Return form
      return $form;

    case 'save':
      return array('openlayers_cck_preset_map');
  }
}

/**
 * Implementation of hook_widget
 */
function openlayers_cck_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  switch ($field['widget']['type']) {
    case 'openlayers_wkt_widget':
      $element = array(
        '#type' => 'openlayers_wkt_widget',
        '#default_value' => $items,
      );
      break;
  }
  return $element;
}

/**
 * Implementation of FAPI hook_elements().
 */
function openlayers_cck_elements() {
  return array(
    'openlayers_cck_geo_field' => array(
      '#input' => TRUE,
      '#columns' => array('openlayers_wkt'),
      '#delta' => 0,
      '#process' => array('openlayers_cck_wkt_element_process'),
    ),
    'openlayers_wkt_widget' => array(
      '#input' => TRUE,
      '#columns' => array('openlayers_wkt'),
      '#delta' => 0,
      '#process' => array('openlayers_cck_wkt_element_process'),
    ),
  );
}

/**
 * Process an individual element.
 */
function openlayers_cck_wkt_element_process($element, $edit, &$form_state, &$form) {
  $field = $form['#field_info'][$element['#parents'][0]];
  $delta = $element['#delta'];
  $field_name = $field['field_name'];
  $widget = $field['widget'];
  $field_label = $widget['label'];
  static $map_included = FALSE;

  // Only include one map
  if ($map_included == FALSE) {
    // Make map for input
    $rendered_map = _openlayers_cck_render_element_map($field_name, $field_label, $element['#value'], $field);
    // Create map element
    $element['map'] = array(
      '#value' => theme('openlayers_cck_map', $field, $rendered_map),
    );
    // Mark as included
    $map_included = TRUE;
  }
  
  // Create storage element
  $element['openlayers_wkt'] = array(
    '#type' => 'textarea',
    '#rows' => 2,
    '#required' => $delta == 0 && $field['required'],
    '#delta' => $delta,
    '#field_name' => $field_name,
    '#type_name' => $field['type_name'],
    '#attributes' => array('rel' => $rendered_map['id']),
  );

  return $element;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function openlayers_cck_field_formatter_info() {
  $formatters = array();
  foreach (openlayers_get_presets() as $name => $title) {
    $formatters['openlayers_cck_formatter_' . $name] = array(
      'label' => t('OpenLayers Map: @preset', array('@preset' => check_plain($title))),
      'field types' => array('geo', 'openlayers_wkt'),
    );
  }
  return $formatters;
}

/**
 * Theme function for openlayers_cck_geo_field element
 */
function theme_openlayers_cck_geo_field($element) {
  return $element['#children'];
}

/**
 * Theme function for openlayers cck formatters
 */
function theme_openlayers_cck_formatter($element) {
  // Get preset name from formatter
  $preset_name = str_replace('openlayers_cck_formatter_', '', $element['#formatter']);
  
  // Get map preset
  $map = openlayers_get_map($preset_name);
  $rendered = openlayers_map_map($map);
  
  // Check for output
  if (empty($map['errors']) && !empty($map['width'])) {
    return $map['themed'];
  }
  else {
    return '';
  }
}

/**
 * Theme function for openlayers_cck_map
 */
function theme_openlayers_cck_map($field = array(), $map = array()) {
  $title = check_plain(t($field['widget']['label']));
  $description = content_filter_xss(t($field['widget']['description']));
  
  $output = '
    <div id="openlayers-cck-map-container-' . $map['id'] . '" class="form-item openlayers-cck-map-container">
      <label for="openlayers-cck-map-' . $map['id'] . '">' . $title . ':</label>
      ' . $map['themed'] . '
      <div class="description openlayers-cck-map-instructions">'.t('Click the tools in the upper right-hand corner of the map to switch between draw mode and zoom/pan mode. Draw your shape, double-clicking to finish. You may edit your shape using the control points. To delete a shape, select it and press the delete key. To delete a vertex hover over it and press the d key.').'</div>
      <div class="description openlayers-cck-map-description">
        ' . $description . '
      </div>
      <div class="openlayers-cck-actions">
        <a href="#" id="' . $map['id'] . '-wkt-switcher" rel="' . $map['id'] . '">'. t('Show/Hide WKT Fields') .'</a>
      </div>
    </div>
  ';
  return $output;
}

/**
 * Render Map for Geo Widget
 *
 * @param $field_name
 *   CCK name of field
 * @param $values
 *   Current default values
 * @param $field
 *   Array of field data
 * @return
 *   Rendered map array
 */
function _openlayers_cck_render_element_map($field_name = '', $field_label = '', $values = array(), $field = array()) {
  $field_name_html = str_replace('_', '-', $field_name);
  $map_id = OPENLAYERS_CCK_MAP_ID_PREFIX .'-'. $field_name;
  $field_container = '';

  // Get default map
  // @TODO: Use widget settings when geo supports it
  $map = openlayers_get_default_map();
  
  // Put together map
  $map['id'] = $map_id;

  // Add main event for CCK processing
  $map['events']['beforeBehaviors'] = array('CCKProcess');
  
  // Define beahvoirs
  $map['behaviors']['openlayers_cck_zoom_to_layer'] = array(
    'id' => 'openlayers_cck_zoom_to_layer',
    'type' => 'openlayers_behaviors_zoom_to_layer',
    'layer' => 'openlayers_cck_vector',
  );
  
  // Make sure that our display projection matches the database projection
  $map['options'] = array(
    'displayProjection' => ($field['srid'] != 0) ? $field['srid'] : '4326',
  );
  
  // Define a vector layer for our features
  $map['layers']['openlayers_cck_vector'] = array(
    'id' => 'openlayers_cck_vector',
    'type' => 'Vector',
    'name' => $field_label,
    'options' => array(),
    'events' => array(
      'featureselected' => array('CCKFeaturesSelected'),
      'featureunselected' => array('CCKFeaturesUnselected'),
    ),
  );
  
  // Build default control without feature type
  $map['behaviors']['openlayers_cck_edit_'. $field['geo_type']] = array(
    'id' => 'openlayers_cck_edit_'. $field['geo_type'],
    'type' => 'openlayers_behaviors_draw_features',
    'layer' => 'openlayers_cck_vector',
    'featureadded_handler' => array('OL.CCK.featureAdded'),
    'featuremodified_handler' => array('OL.CCK.featureModified'),
    'featureremoved_handler' => array('OL.CCK.featureRemoved'),
  );
  
  // Determine type from geo type
  switch ($field['geo_type']) {
    case 'point':
      $map['behaviors']['openlayers_cck_edit_'. $field['geo_type']]['feature_type'] = 'point';
      break;
    
    case 'linestring':
      $map['behaviors']['openlayers_cck_edit_'. $field['geo_type']]['feature_type'] = 'path';
      break;
      
    case 'polygon':
      $map['behaviors']['openlayers_cck_edit_'. $field['geo_type']]['feature_type'] = 'polygon';
      break;
  }
  
  // Check if multiple, as there are specific needs
  if (empty($field['multiple'])) {
    // If a single value
    $field_container = 'edit-' . $field_name_html . '-0-geo-geo-wkt-wrapper';
  }
  else {
    // For multiples, we need to move out map widget outside of the fields
    $field_container = $field_name . '_values';
    // Call Move Map event
    $map['events']['beforeEverything'] = array('CCKMoveMap');
  }
  
  // Render Map
  $rendered_map = openlayers_render_map($map);
  
  // Check errors
  if (!$rendered_map['errors']) {
    // Add JS
    drupal_add_js(drupal_get_path('module', 'openlayers_cck') .'/js/openlayers_cck.js');
    //Add CSS
    drupal_add_css(drupal_get_path('module', 'openlayers_cck') .'/openlayers_cck.css', 'module');
    
    // Put together array for JS
    $openlayers_cck = array(
      'openlayers_cck' => array(
        'maps' => array(
          $map_id => array(
            'field_name' => $field_name,
            'field_data' => $field,
            'field_name_js' => $field_name_html,
            'field_container' => $field_container,
            'field_items' => $items,
            'map_container' => 'openlayers-cck-map-container-' . $map_id,
          ),
        ),
      ),
    );

    // Add JS settings
    drupal_add_js($openlayers_cck, 'setting');
  }

  return $rendered_map;
}