<?php
// $Id$

/**
 * @file
 * This file holds the main Drupal hook functions
 * and private functions for the openlayers_views module.
 *
 * @ingroup openlayers
 */

/**
 * Map ID Prefix
 */
define('OPENLAYERS_VIEWS_MAP_ID_PREFIX', 'openlayers-views-map-auto-id');

/**
 * Implementation of hook_help().
 */
function openlayers_views_help($path, $arg) {
  $output = '';

  switch ($path) {
    case 'admin/help#openlayers_views':
      $output = '<p>'. t('The OpenLayers Views module provides a set of plugins for Views.') .'</p>';
      return $output;

  }
}

/**
 * Implementation of hook_theme().
 */
function openlayers_views_theme($existing, $type, $theme, $path) {
  return array(
    'openlayers_views_feature_style' => array(
      'arguments' => array(
        'view' => NULL,
        'row' => NULL,
        'group' => NULL,
      ),
      'file' => 'includes/openlayers_views.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function openlayers_views_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'openlayers_views') .'/views',
  );
}



/**
 * Implementation of hook_openlayers_layers_info().
 */
function openlayers_views_openlayers_layers_info() {
  $layers = array();

  $views = views_get_all_views();
  /**
   * Loop through views for displays generatd by the openlayers data style plugin.  Provide each as
   * available layer for map presets
   *
   * @Todo: think about what settings should be allowed to be defined by the view display options,
   *        what should be automatic, and what to configure on the map preset level
   *
   */
  foreach ($views as $view) {
    foreach ($view->display as $display => $data) {
      if ($data->display_options['style_plugin'] == 'openlayers_data') {
        // @@TODO: Needs to be plug-in-ized
        $layer = array (
          'id' => 'openlayers_views_' . $view->name . '_' . $display, 
          'name' => $data->display_options['title'] ? $data->display_options['title'] : $view->display['default']->display_options['title'], 
          'description' => $view->description . ' - ' . $data->display_title, 
          'baselayer' => FALSE,
          'views' => array('view' => $view->name, 'display' => $display),
          'file' => drupal_get_path('module', 'openlayers_views') .'/includes/openlayers_views.layers.inc',
          'callback' => 'openlayers_views_process_layers',
        );
        $layers[$layer['id']] = $layer;
      }
    }
  }
  return $layers;
}
