<?php
// $Id$

/**
 * Implementation of hook_help
 */
function openlayers_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/help#openlayers_ui':
      $output = '<p>'. t('Provides a user interface to manage OpenLayers maps.') .'</p>';
  }

  return $output;
}

/**
 * Implementation of hook_menu
 */
function openlayers_ui_menu() {
  $items = array();

  // Core OpenLayers settings pages.
  $items['admin/settings/openlayers'] = array(
    'title' => 'OpenLayers',
    'description' => t('Main settings for OpenLayers.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_admin_settings'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/settings/openlayers/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );

  // Layers.
  $items['admin/settings/openlayers/layers'] = array(
    'title' => 'Layers',
    'page callback' => 'openlayers_ui_object_list',
    'page arguments' => array(3),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/layers/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );
  // Layer type drilldown
  $items['admin/settings/openlayers/layers/add'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_layers_types'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  // Actual add-layer form
  $items['admin/settings/openlayers/layers/add/%openlayers_layer_type'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_layers_form', 5),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -15,
  );
  // Actual add-layer form
  $items['admin/settings/openlayers/layers/clone/%openlayers_layer'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_layers_form', 5),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -15,
  );
  // Edit-layer form
  $items['admin/settings/openlayers/layers/%openlayers_layer/edit'] = array(
    'title' => 'Edit layer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_layers_form', 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/settings/openlayers/layers/%openlayers_layer_export/delete'] = array(
    'title' => 'Delete layer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_delete', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/settings/openlayers/layers/%openlayers_layer/export'] = array(
    'title' => 'Export layer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_export', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  // Layer-type-wide settings form
  $items['admin/settings/openlayers/layers/settings'] = array(
    'title' => 'API Keys',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_layers_settings'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );

  // Styles.
  $items['admin/settings/openlayers/styles'] = array(
    'title' => 'Styles',
    'page callback' => 'openlayers_ui_object_list',
    'page arguments' => array(3),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/styles/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );
  $items['admin/settings/openlayers/styles/add'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_styles_form'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/styles/add/%openlayers_style'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_styles_form', 5),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/styles/%openlayers_style/edit'] = array(
    'title' => 'Edit style',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_styles_form', 4, TRUE),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/settings/openlayers/styles/%openlayers_style/delete'] = array(
    'title' => 'Delete style',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_delete', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/settings/openlayers/styles/%openlayers_style/export'] = array(
    'title' => 'Export style',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_export', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  // Presets.
  $items['admin/settings/openlayers/presets'] = array(
    'title' => 'Presets',
    'description' => t('Create OpenLayers map presets.'),
    'page callback' => 'openlayers_ui_object_list',
    'page arguments' => array(3),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/presets/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );
  $items['admin/settings/openlayers/presets/add'] = array(
    'title' => 'Add',
    'description' => t('Add OpenLayers map preset.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_presets_form'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/presets/add/%openlayers_preset'] = array(
    'title' => 'Clone Preset',
    'description' => t('Add OpenLayers map preset.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_presets_form', 5),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
  );
  $items['admin/settings/openlayers/presets/%openlayers_preset/edit'] = array(
    'title' => 'Edit preset',
    'description' => 'Edit OpenLayers map preset.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_presets_form', 4, TRUE),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'tab_parent' => 'admin/settings/openlayers/presets',
  );
  $items['admin/settings/openlayers/presets/%openlayers_preset/delete'] = array(
    'title' => 'Delete preset',
    'description' => 'Delete OpenLayers map preset.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_delete', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'tab_parent' => 'admin/settings/openlayers/presets',
  );
  $items['admin/settings/openlayers/presets/%openlayers_preset/export'] = array(
    'title' => 'Export preset',
    'description' => t('Export OpenLayers map preset.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_object_export', 3, 4),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'tab_parent' => 'admin/settings/openlayers/presets',
  );
  $items['openlayers/ahah/preset'] = array(
    'title' => 'OpenLayers AHAH',
    'page callback' => 'openlayers_ui_preset_ahah',
    'access callback' => TRUE,
    'file' => 'includes/openlayers.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function openlayers_ui_theme($existing, $type, $theme, $path) {
  return array(
    'openlayers_ui_form_layer_description' => array(
      'arguments' => array(
        'layer_title' => '',
        'layer_description' => '',
      ),
      'file' => 'includes/openlayers.admin_theme.inc',
    ),
    'openlayers_ui_form_projection_description' => array(
      'arguments' => array(
        'projection_title' => '',
        'available_layers' => array(),
        'layers' => array(),
      ),
      'file' => 'includes/openlayers.admin_theme.inc',
    ),
    'openlayers_ui_presets_form' => array(
      'arguments' => array('form' => array()),
      'file' => 'includes/openlayers.admin_theme.inc',
    ),
    'openlayers_ui_presets_form_layers' => array(
      'arguments' => array('form' => array()),
      'file' => 'includes/openlayers.admin_theme.inc',
    ),
  );
}
