<?php

/**
 * Implements hook_menu
 */
function openlayers_ui_menu() {
  $items = array();

  // Core OpenLayers settings pages.
  $items['admin/structure/openlayers'] = array(
    'title' => 'OpenLayers',
    'description' => 'Manage maps, layers, sources, controls, styles, and interactions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_admin_settings'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/structure/openlayers/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -20,
  );

 return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function openlayers_ui_ctools_plugin_directory($module, $type) {
  if ($type == 'export_ui') {
    return 'plugins/export_ui';
  }
}
