<?php
// $Id$

/**
 * @file
 * This file holds the main Drupal hook functions 
 * and private functions for the openlayers_layers module.
 *
 * @ingroup openlayers
 */

/**
 * Implementation of hook_help
 */
function openlayers_layers_help($path, $arg) {
  switch ($path) {
    case 'admin/help#openlayers_layers':
      $output = '<p>'. t('Provides a wide variety of freely available layers.') .'</p>';
  }
  return $output;
}

/**
 * Implementation of hook_menu
 */
function openlayers_layers_menu() {
  $items = array();
  $items['admin/settings/openlayers/openlayers_layers'] = array(
    'title' => 'Layers Settings',
    'description' => 'Set your API keys here',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_layers_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
   );
  return $items;
}

/**
 * Menu callback; displays the openlayers_layers module settings page.
 *
 * @ingroup forms
 * @see system_settings_form()
 */
function openlayers_layers_admin_settings() {
  $form = array();

  $form['openlayers_layers_google_api'] = array(
    '#type' => 'textfield',
    '#title' => t('Google Maps API Key'),
    '#description' => t("Your personal Googlemaps API key.  You must get this for each separate website at <a href='http://www.google.com/apis/maps/'>Google Map API website</a>."),
    '#default_value' => variable_get('openlayers_layers_google_api', variable_get('googlemap_api_key', '')),
  );
  
  $form['openlayers_layers_yahoo_api'] = array(
    '#type' => 'textfield',
    '#title' => t('Yahoo Maps API Key'),
    '#description' => t("Your personal Yahoo API key.  You must get this for each separate website at <a href='http://developer.yahoo.com/maps/'>Yahoo Maps API website</a>."),
    '#default_value' => variable_get('openlayers_layers_yahoo_api',''),
  );  
  
  return system_settings_form($form);
}

/**
 * Implemnetation of hook_openlayers_layers_handler
 *
 * Define Layer Types that won't be used outside of this module such as Google Maps, Yahoo Maps, and MS Virtual Earth
 */
function openlayers_layers_openlayers_layers_handler_info($map = array()) {
  
  return array(
    'KML' => array(
      'layer_handler' => 'openlayersLayerHandlerKML',
      'js_file' => drupal_get_path('module', 'openlayers_layers') .'/js/openlayers_layers_layers.js',
    ),
    'XYZ' => array(
      'layer_handler' => 'openlayersLayerHandlerXYZ',
      'js_file' => drupal_get_path('module', 'openlayers_layers') .'/js/openlayers_layers_layers.js',
    ),
    'Google' => array(
      'layer_handler' => 'openlayersLayerHandlerGoogle',
      'js_file' => drupal_get_path('module', 'openlayers_layers') .'/js/openlayers_layers_layers.js',
    ),
    'VirtualEarth' => array(
      'layer_handler' => 'openlayersLayerHandlerVirtualEarth',
      'js_file' => drupal_get_path('module', 'openlayers_layers') .'/js/openlayers_layers_layers.js',
    ),
    'Yahoo' => array(
      'layer_handler' => 'openlayersLayerHandlerYahoo',
      'js_file' => drupal_get_path('module', 'openlayers_layers') .'/js/openlayers_layers_layers.js',
    ),
  );
}


/**
 * Implementation of hook_openlayers_layers_info
 */
function openlayers_layers_openlayers_layers_info() {
  $file = drupal_get_path('module', 'openlayers_layers') .'/includes/openlayers_layers.layers.inc';
  $callback = 'openlayers_layers_process_layers';
  $info = array();
  
  // Define info array
  $info['openlayers_layers_nasa_global_mosaic'] = array(
    'name' => t('NASA Global Mosaic'),
    'description' => t('A high resolution global image mosaic of the earth, produced from 1999-2003 Landsat7 scenes. The highest resolution has a resolution of 15 meters.'),
    'projection' => array('4326'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => $callback,
  );
  
  $info['openlayers_layers_nasa_daily_planet'] = array(
    'name' => t('NASA Daily Planet'),
    'description' => t('This layer is the most current, near-global image of the earth available. It is a countinuously updating image from the MODIS TERRA satellite'),
    'projection' => array('4326'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => $callback,
  );
  
  $info['openlayers_layers_nasa_blue_marble'] = array(
    'name' => t('NASA Blue Marbel'),
    'description' => t('Blue Marble Next Generation, A MODIS-derived 500m true color earth dataset showing seasonal dynamics. This version of the BMNG was updated June 2007'),
    'projection' => array('4326'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => $callback,
  );
  
  $info['openlayers_layers_open_aerial'] = array(
    'name' => t('Open Aerial (2.8 - do not use)'),
    'description' => t('OpenAerialMap is an open collection of aerial photographs, collected into a single coherent view of the world.'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => $callback,
  );
  
  $info['openlayers_layers_google_street'] = array(
    'name' => t('Google Street'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_google_satellite'] = array(
    'name' => t('Google Satellite'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_google_hybrid'] = array(
    'name' => t('Google Hybrid'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_google_physical'] = array(
    'name' => t('Google Physical'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_yahoo_street'] = array(
    'name' => t('Yahoo Street'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_yahoo_satellite'] = array(
    'name' => t('Yahoo Satellite'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_yahoo_hybrid'] = array(
    'name' => t('Yahoo Hybrid'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_virtual_earth_street'] = array(
    'name' => t('Virtual Earth Street'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_virtual_earth_satellite'] = array(
    'name' => t('Virtual Earth Satellite'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_virtual_earth_hybrid'] = array(
    'name' => t('Virtual Earth Hybrid'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_osm_mapnik'] = array(
    'name' => t('OSM Mapnik (2.8 - do not use)'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_osm_tah'] = array(
    'name' => t('OSM Tiles@Home (2.8 - do not use)'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  $info['openlayers_layers_osm_cycle'] = array(
    'name' => t('OSM Cycling Map (2.8 - do not use)'),
    'projection' => array('900913'),
    'baselayer' => TRUE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );

  $info['openlayers_layers_osm_4326_hybrid'] = array(
    'name' => t('OSM Overlay'),
    'description' => t('Semi-transparent hybrid overlay. Projectd into WSG84 for use on non spherical-mercator maps.'),
    'projection' => array('4326'),
    'baselayer' => FALSE,
    'file' => $file,
    'callback' => 'openlayers_layers_process_layers',
  );
  
  // Module Dependant Layer Instances
  if (module_exists('kml')){
    $info['openlayers_layers_local_kml'] = array(
      'name' => t('Local KML Feed'),
      'file' => $file,
      'callback' => 'openlayers_layers_process_layers',
    );
  }

  if (module_exists('geo_data')){
    // Get the data tables loaded from shapefiles, and include them as available layers
    $geo_tables  = geo('tables', '/^content_field/');
    foreach ($geo_tables as $key => $table){
      $info[$key] = array (
        // @@TODO: Actually have a real name
        'name' => $key,
        'file' => $file,
        'callback' => 'openlayers_layers_process_geo_data_layers',
      );
    }
  }
  
  return $info;
}
